version: '3'
services:

  pg-database:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - /home/blaise/dataEngineeringZoomCamp/weekOneRemontada/docker_sql/ny_taxi_postgres_data:/var/lib/postgresql/data
    ports:
      - 5000:5432
    
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - pg-database
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root 
    ports:
      - 8080:80